# Generated by Django 3.2.5 on 2021-10-17 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_employee_eid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edescripcion', models.TextField(max_length=256)),
                ('epresupuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.presupuesto')),
            ],
            options={
                'db_table': 'placas',
            },
        ),
    ]
