# Generated by Django 3.2.5 on 2021-10-17 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_placas'),
    ]

    operations = [
        migrations.AddField(
            model_name='placas',
            name='etipo',
            field=models.CharField(choices=[('EL-1655', 'EL-1655'), ('EL-1656', 'EL-1656'), ('EL-1666', 'EL-1666')], default='EL-1655', max_length=8),
            preserve_default=False,
        ),
    ]
