# Generated by Django 3.2.5 on 2021-10-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_placas_etipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='placas',
            name='PE',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='placas',
            name='QA',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='placas',
            name='QC',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='placas',
            name='ePEM',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placas',
            name='ecalidad',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placas',
            name='ecompras',
            field=models.CharField(default='T&R', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placas',
            name='efaz',
            field=models.CharField(choices=[('SIMPLE', 'SIMPLE'), ('DOBLE', 'DOBLE')], default='SIMPLE', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placas',
            name='elote',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placas',
            name='emaduro',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placas',
            name='epolimeros',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placas',
            name='qBGA_CCGA',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placas',
            name='qBOM',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placas',
            name='qaut',
            field=models.IntegerField(default=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placas',
            name='qcomponentes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placas',
            name='qfine_pitch',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placas',
            name='qpads',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placas',
            name='qplacas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placas',
            name='edescripcion',
            field=models.TextField(blank=True, max_length=256),
        ),
    ]
