# Generated by Django 3.2.5 on 2021-10-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211020_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placas',
            name='qpads',
            field=models.PositiveIntegerField(),
        ),
    ]
